SalesSystem/Models/ErrorViewModel.cs
namespace SalesSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SalesSystem/Models/ServiceClient.cs
using SalesSystem.Data;
using SalesSystem.Utilities;

namespace SalesSystem.Models
{
    public class ServiceClient
    {
        public List<Client> GetAllActiveUsers()
        {
            return new RepositoryClient().GetAllActiveUsers();
        }

        public bool DeleteClient(int Id)
        {
            return new RepositoryClient().DeleteClient(Id);
        }

    }
}

SalesSystem/Models/ServiceVehicle.cs
using SalesSystem.Data;
using SalesSystem.Utilities;

namespace SalesSystem.Models
{
    public class ServiceVehicle
    {
        public bool InsertVehicle(Vehicle vehicle)
        {
            return new RepositoryVehicle().InsertVehicle(vehicle);
        }


        public List<Vehicle> SelectAllActiveVehicles()
        {
            return new RepositoryVehicle().SelectAllActiveVehicles();
        }
    }
}

SalesSystem/Controllers/ClientController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SalesSystem.Models;
using SalesSystem.Utilities;

namespace SalesSystem.Controllers
{
    public class ClientController : Controller
    {
        // GET: ClientController
        public ActionResult ListClient()
        {
            List<Client> listclient = new ServiceClient().GetAllActiveUsers();
            return View(listclient);
        }


        // GET: ClientController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientController/Delete/5
        public ActionResult Delete(int id)
        {
            bool result = new ServiceClient().DeleteClient(id);
            if (result)
            {
                return RedirectToAction("ListClient", "Client");
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ClientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SalesSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SalesSystem.Models;
using System.Diagnostics;

namespace SalesSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SalesSystem/Controllers/SalesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SalesSystem.Controllers
{
    public class SalesController : Controller
    {
        // GET: SalesController
        public ActionResult List()
        {
            return View();
        }

        // GET: SalesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SalesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SalesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SalesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SalesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SalesSystem/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using SalesSystem.Models;
using SalesSystem.Utilities;

namespace SalesSystem.Controllers
{
    public class VehicleController : Controller
    {
        // GET: VehicleController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListVehicles()
        {
            List<Vehicle> vehicles = new ServiceVehicle().SelectAllActiveVehicles();
            return View(vehicles);
        }

        // GET: VehicleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VehicleController/Create
        public ActionResult Create()
        {

            return View();

        }

        // POST: VehicleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehicle vehicle)
        {
            vehicle.Entry = DateAndTime.Now;
            vehicle.Status = 1;
            bool respuesta = new ServiceVehicle().InsertVehicle(vehicle);
            if (respuesta)
            {
                return RedirectToAction("ListVehicles");
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: VehicleController/Edit/5
        public ActionResult Edit(int id)
        { 
            return View();
        }

        // POST: VehicleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VehicleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VehicleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SalesSystem/Views/Client/Create.cshtml
@model SalesSystem.Utilities.Client

@{
    ViewData["Title"] = "Nuevo Cliente";
}

<h1>Crear Cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birth" class="control-label"></label>
                <input asp-for="Birth" class="form-control" />
                <span asp-validation-for="Birth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label"></label>
                <input asp-for="RegisterDate" class="form-control" />
                <span asp-validation-for="RegisterDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem/Views/Client/Edit.cshtml
@model SalesSystem.Utilities.Client

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birth" class="control-label"></label>
                <input asp-for="Birth" class="form-control" />
                <span asp-validation-for="Birth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label"></label>
                <input asp-for="RegisterDate" class="form-control" />
                <span asp-validation-for="RegisterDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem/Views/Client/Index.cshtml
@model IEnumerable<SalesSystem.Utilities.Client>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegisterDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisterDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

SalesSystem/Views/Client/ListClient.cshtml
@model IEnumerable<SalesSystem.Utilities.Client>

@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<p>
    <a asp-controller="ClientController" asp-action="Create" class="btn effect01 m-2"><i class="fa-solid fa-user-plus"></i> Nuevo Cliente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Código
            </th>
            <th>
                DNI
            </th>
            <th>
                Nombre
            </th>
            <th>
                I Apellido
            </th>
            <th>
                II Apellido
            </th>
            <th>
                Correo
            </th>
            <th>
                Nacimiento
            </th>
            <th>
                Celular
            </th>
            <th>
                Teléfono
            </th>
            <th>
                Opciones
            </th>
        </tr>
    </thead>
    <tbody>
        @{
           int line = 1; 
        }
        @foreach (var item in Model) {
        <tr>
            <td>
                @line
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                <a asp-controller="ClientController" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary"><i class="fa-solid fa-user-pen"></i></a>
                <a asp-controller="ClientController" asp-action="Details" asp-route-id="@item.Id" class="btn btn-success"><i class="fa-solid fa-address-card"></i></a>
                <a asp-controller="ClientController" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa-solid fa-user-xmark"></i></a>
            </td>
        </tr>
            line++;
}
    </tbody>
</table>

SalesSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4">Venta de Vehiculos</h1>
    <h1 class="display-4">Inicio</h1>

    <a asp-controller="Client" asp-action="Create" class="btn effect01 m-2"><i class="fa-solid fa-user-plus"></i> Nuevo Cliente</a>
    <a asp-controller="Client" asp-action="ListClient" class="btn effect01 m-2"><i class="fa-solid fa-people-line"></i> Clientes</a>

    <a asp-controller="Vehicle" asp-action="Create" class="btn effect01 m-2"><i class="fa-solid fa-car-rear"></i> Nuevo Veh&iacute;culo</a>
    <a asp-controller="Vehicle" asp-action="ListVehicles" class="btn effect01 m-2"><i class="fa-regular fa-rectangle-list"></i> Veh&iacute;culos</a>

    <a asp-controller="Sales" asp-action="Create" class="btn effect01 m-2"><i class="fa-solid fa-truck-pickup"></i> Facturar</a>
    <a asp-controller="Sales" asp-action="List" class="btn effect01 m-2"><i class="fa-solid fa-clipboard-list"></i> Facturas</a>


    
    <p>Sistema de Venta para Vehículos</p>
</div>

SalesSystem/Views/Sales/Create.cshtml
@model SalesSystem.Utilities.Bill

@{
    ViewData["Title"] = "Facturar";
}

<h1>Facturací&oacute;n</h1>

<h4>Factura</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" value="0" class="form-control" hidden />
            </div>
            <div class="form-group">
                <label asp-for="Consecutive" class="control-label">Consecutivo</label>
                <input asp-for="Consecutive" class="form-control" value="000000000000000"/>
                <span asp-validation-for="Consecutive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumericalKey" class="control-label">Clave Num&eacute;rica</label>
                <input asp-for="NumericalKey" class="form-control" value="0000000000"/>
                <span asp-validation-for="NumericalKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InternalCode" class="control-label">N&uacute;mero</label>
                <input asp-for="InternalCode" class="form-control"/>
                <span asp-validation-for="InternalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesPerson" class="control-label">Vendedor</label>
                <select name="SalesPerson" asp-for="SalesPerson" class="form-control">
                    <option value="1">Karla Espinoza</option>
                    <option value="2">Andrey Arguedas</option>
                    <option value="3">Mario Mora</option>
                    <option value="4">Gabriela Perez</option>
                </select>
                <span asp-validation-for="SalesPerson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Client" class="control-label">Cliente</label>
                <input asp-for="Client" class="form-control" placeholder="Cliente" />
                <input type="text" class="form-control" placeholder="Nombre"/>
                <span asp-validation-for="Client" class="text-danger"></span>
            </div>


            <table class="table table-responsive table-hover table-secondary">
                <thead>
                <tr>
                    <td>#</td>
                    <td>C&oacute;digo</td>
                    <td>Modelo</td>
                    <td>Marca</td>
                    <td>Precio</td>
                    <td>IVA</td>
                    <td>Total</td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>1027</td>
                    <td>Frontier</td>
                    <td>Nissan</td>
                    <td>37 600</td>
                    <td>4888</td>
                    <td>42488</td>
                    <td><a class="btn btn-danger"><i class="fa-solid fa-circle-minus"></i></a></td>
                </tr>
            </tbody>
            </table>


            <div class="form-group">
                <label asp-for="Price" class="control-label">Precio</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IVA" class="control-label"></label>
                <input asp-for="IVA" class="form-control" />
                <span asp-validation-for="IVA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SalesSystem/Views/Vehicle/ListVehicles.cshtml
@model IEnumerable<SalesSystem.Utilities.Vehicle>

@{
    ViewData["Title"] = "Vehicles";
}

<h1>Vehicles</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               #
            </th>
            <th>
                Código
            </th>
            <th>
                Modelo
            </th>
            <th>
                Marca
            </th>
            <th>
                Año
            </th>
            <th>
                Color
            </th>
            <th>
                Pasajeros
            </th>
            <th>
                Llantas
            </th>
            <th>
                Motor
            </th>
            <th>
                Combustible
            </th>
            <th>
                Deposito
            </th>
            <th>
                Tipo
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Precio
            </th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>

        @{
            int line = 0;
        }
        @foreach (var item in Model) {
        <tr>
            <td>
                @line
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mark)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passenger)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tire)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Engine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fuel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                    <a asp-controller="Vehicle" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary"><i class="fa-solid fa-car-burst"></i></a>
                    <a asp-controller="Vehicle" asp-action="Details" asp-route-id="@item.Id" class="btn btn-success"><i class="fa-solid fa-car-side"></i></a>
                    <a asp-controller="Vehicle" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="fa-solid fa-delete-left"></i></a>
            </td>
        </tr>
        line++;
}
    </tbody>
</table>